server:
  port: 80
  sources:
    - path: /share
      config:
        defaultEnabled: true
        
frontend:
  name: "Servidor-1"
auth:
  adminUsername: admin
  adminPassword: admin
  methods:
    password:
      enabled: true
      
integrations:
  media:
    ffmpegPath: "/usr/local/bin"
  office:
    url: "http://188.213.5.144:8080"   # http://localhost:8080
#    internalUrl: "http://localhost:80"
    secret: TevrjpRNMmKC0JxAwY7iZ2VXLrvG1gue    
#    - JWT_SECRET=TevrjpRNMmKC0JxAwY7iZ2VXLrvG1gue
