server:
  sources:
    - path: "./share"
      config:
        defaultEnabled: true
        
frontend:
  name: "Servidor-1"
auth:
  adminUsername: admin
  adminPassword: admin
  methods:
    password:
      enabled: true
      
integrations:
  media:
    ffmpegPath: "/usr/local/bin" 
    
  # Office integration (OnlyOffice)
  office:
    url: "http://localhost:8080"
    secret: TevrjpRNMmKC0JxAwY7iZ2VXLrvG1gue
