server:
  sources:
    - path: "./share"
      config:
        defaultEnabled: true
        
frontend:
  name: "Servidor-1"
auth:
  adminUsername: admin
  adminPassword: admin
  methods:
    password:
      enabled: true
      
integrations:
  # Office integration (OnlyOffice)
  office:
    url: "http://188.213.5.144:8080"   # http://localhost:8080

onlyoffice:
  environment:
    - JWT_ENABLED=true
    - JWT_SECRET=TevrjpRNMmKC0JxAwY7iZ2VXLrvG1gue
