server:
  sources:
    - path: "./share"
      config:
        defaultEnabled: true
frontend:
  name: "Servidor-1"
auth:
  adminUsername: admin
  adminPassword: admin
  methods:
    password:
      enabled: true
